This code snipet references: https://www.tensorflow.org/tutorials/eager/eager_basics.

The default behavior of tensorflow (at least up to R1.11) is to create computational graphs as one code in tensorflow. This means no actual computation is done until it is explicitly requested to do so through the use of a dedicated session. **With eager execution, computation is executed at each line of code.** This is much more similar to traditional programming behavior, that each line of code is executed immediately at compile time.

### 1. Set Up Eager Execution

To turn on eager execution mode, simply add the `tf.enable_eager_execution()` line right after importing tensorflow.

In [11]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

### 2. Computation
Under eager execution mode, computations on tensors are carried out immediately.

In [10]:
print(tf.add(1,2))
print(tf.subtract(5,3))
print(tf.multiply(7,7))
print(tf.div(35,7))
print(tf.square(9))
print(tf.reduce_sum([1,2,3,4,5]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(49, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


### 3. Conversion between Numpy Arrays & Tensors

Conversions between numpy arrays and tensors also become easy

In [20]:
# Ex. from np.array to tensor
test = np.array([[[1,2,3],[2,3,4],[3,4,5]],
                 [[4,5,6],[5,6,7],[6,7,8]],
                 [[5,6,7],[6,7,8],[7,8,9]]])
print(type(test), test.shape)
test = tf.convert_to_tensor(test)
print(type(test), test.get_shape())

<class 'numpy.ndarray'> (3, 3, 3)
<class 'tensorflow.python.framework.ops.EagerTensor'> (3, 3, 3)


In [24]:
# Ex. from tensor to np.array
test = tf.constant([[[1,2,3],[2,3,4],[3,4,5]],
                    [[4,5,6],[5,6,7],[6,7,8]],
                    [[5,6,7],[6,7,8],[7,8,9]]])
print(type(test), test.get_shape())
test = test.numpy()
print(type(test), test.shape)

<class 'tensorflow.python.framework.ops.EagerTensor'> (3, 3, 3)
<class 'numpy.ndarray'> (3, 3, 3)


Furthermore, operations between numpy arrays and tensors get handled automatically:

In [28]:
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor,'\n')

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64) 

And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


### 4. Working with tf.Dataset

Under eager execution mode, the tf.Dataset object becomes iterable. This means it can be applied with a normal Python for loop!

In [33]:
data1 = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])
# apply transformation as part of data pipeline, shuffle and batch
data1 = data1.map(tf.square).shuffle(6).batch(2)

# iterate over the data batch created from data1
for data_batch in data1:
    print(data_batch)

tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([ 1 36], shape=(2,), dtype=int32)
